### ISSUE TITLE
TypeError after nominally successful simulation run 

### ISSUE THREAD

**Issue by gvoysey** [SmokinCaterpillar/pypet#37]
Running [this](https://github.com/gvoysey/thesis-code/blob/727b76b8d2af9d3e4217bd439f6d98c02ff1924c/scripts/tone_in_noise/tone-in-noise.py) script, patterned on the simple docs example, results in a type error.  It is not clear to me how to determine what's `None` that shouldn't be.   

```
MainProcess root INFO     Simulation finished.
MainProcess pypet.storageservice.HDF5StorageService INFO     Processed 15 nodes in 0m26s (0.58 nodes/s).
MainProcess pypet.storageservice.HDF5StorageService ERROR    Failed storing table `config` of `results.runs.run_00000000.periphery.config`.
MainProcess pypet.storageservice.HDF5StorageService ERROR    Failed storing leaf `results.runs.run_00000000.periphery.config`. I will remove the hdf5 data I added  again.
MainProcess pypet.storageservice.HDF5StorageService ERROR    Failed storing `Trajectory (during single run) tone-in-noise (`some comment`, len:1): (config: <class 'pypet.naturalnaming.ConfigGroup'>), (results: <class 'pypet.naturalnaming.ResultGroup'>), (parameters: <class 'pypet.naturalnaming.ParameterGroup'>)`
MainProcess pypet ERROR    ERROR occurred during a single run! 
Traceback (most recent call last):
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/environment.py", line 260, in _sigint_handling_single_run
    return _single_run(kwargs)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/environment.py", line 319, in _single_run
    traj.f_store()
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/utils/decorators.py", line 165, in new_func
    return func(*args, **kwargs)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/utils/decorators.py", line 165, in new_func
    return func(*args, **kwargs)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/utils/decorators.py", line 123, in new_func
    return func(*args, **kwargs)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/trajectory.py", line 2873, in f_store
    max_depth=max_depth)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 1298, in store
    self._srn_store_single_run(stuff_to_store, *args, **kwargs)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 2892, in _srn_store_single_run
    hdf5_group=None)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 2631, in _tree_store_sub_branch
    parent_hdf5_group=hdf5_group)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 2824, in _tree_store_nodes_dfs
    _newly_created=newly_created)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 4003, in _prm_store_parameter_or_result
    self._prm_store_from_dict(fullname, store_dict, _hdf5_group, store_flags, kwargs)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 3858, in _prm_store_from_dict
    **kwargs)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 4182, in _prm_write_dict_as_table
    self._prm_write_into_pytable(key, objtable, group, fullname, **kwargs)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 4485, in _prm_write_into_pytable
    description_dict, data_type_dict = self._prm_make_description(data, fullname)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 4605, in _prm_make_description
    key)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 3100, in _all_set_attributes_to_recall_natives
    (str(data), repr(type(data))))
TypeError: I do not know how to handle `None` its type is `<class 'NoneType'>`.
Traceback (most recent call last):
  File "/Users/gvoysey/Projects/thesis-code/scripts/tone_in_noise/tone-in-noise.py", line 98, in <module>
    sys.exit(main())
  File "/Users/gvoysey/Projects/thesis-code/scripts/tone_in_noise/tone-in-noise.py", line 93, in main
    env.run(tone_in_noise)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/environment.py", line 1807, in run
    return self._execute_runs(pipeline)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/environment.py", line 2330, in _execute_runs
    self._inner_run_loop(results)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/environment.py", line 2473, in _inner_run_loop
    result = _sigint_handling_single_run(task)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/environment.py", line 260, in _sigint_handling_single_run
    return _single_run(kwargs)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/environment.py", line 319, in _single_run
    traj.f_store()
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/utils/decorators.py", line 165, in new_func
    return func(*args, **kwargs)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/utils/decorators.py", line 165, in new_func
    return func(*args, **kwargs)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/utils/decorators.py", line 123, in new_func
    return func(*args, **kwargs)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/trajectory.py", line 2873, in f_store
    max_depth=max_depth)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 1298, in store
    self._srn_store_single_run(stuff_to_store, *args, **kwargs)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 2892, in _srn_store_single_run
    hdf5_group=None)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 2631, in _tree_store_sub_branch
    parent_hdf5_group=hdf5_group)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 2824, in _tree_store_nodes_dfs
    _newly_created=newly_created)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 4003, in _prm_store_parameter_or_result
    self._prm_store_from_dict(fullname, store_dict, _hdf5_group, store_flags, kwargs)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 3858, in _prm_store_from_dict
    **kwargs)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 4182, in _prm_write_dict_as_table
    self._prm_write_into_pytable(key, objtable, group, fullname, **kwargs)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 4485, in _prm_write_into_pytable
    description_dict, data_type_dict = self._prm_make_description(data, fullname)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 4605, in _prm_make_description
    key)
  File "/Users/gvoysey/verhulst-install/lib/python3.5/site-packages/pypet/storageservice.py", line 3100, in _all_set_attributes_to_recall_natives
    (str(data), repr(type(data))))
TypeError: I do not know how to handle `None` its type is `<class 'NoneType'>`.

Process finished with exit code 1
```

**Comment by SmokinCaterpillar** [comment]
Hi *pypet* does not support ``None`` as data.

According to this ERROR message:
``MainProcess pypet.storageservice.HDF5StorageService ERROR    Failed storing table `config` of `results.runs.run_00000000.periphery.config`.``
there seems to be some ``None`` value item in your  config dictionary that you store in each run  (although here it's called ``conf``, did you change names?):
``traj.f_add_result('periphery.conf', periphery.conf.__dict__, "")``.

You can try to remove all data that is ``None``:

    conf_dict = {key:value for key, value in periphery.conf.__dict__.items() if value is not None}
    traj.f_add_result('periphery.conf', conf_dict)
