### ISSUE TITLE
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

### ISSUE THREAD

**Issue by Felix11H** [SmokinCaterpillar/pypet#51]
This seems to happen when I run a rather large Brian2 simulation. I wasn't able to test this a lot so far, and I'm not even sure this error is anything that Pypet can fix. What I can report, is that the error does not occur for short simulation times and does not depend on how many runs are made in parallel (tested: 2, 10).

Any ideas? Maybe this looks familiar to anyone? Thanks!

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hoffmann/dev/pypet-fork/pypet/pypet/environment.py", line 132, in _process_single_run
    result = _sigint_handling_single_run(kwargs)
  File "/home/hoffmann/dev/pypet-fork/pypet/pypet/environment.py", line 259, in _sigint_handling_single_run
    return _single_run(kwargs)
  File "/home/hoffmann/dev/pypet-fork/pypet/pypet/environment.py", line 318, in _single_run
    traj.f_store()
  File "/home/hoffmann/dev/pypet-fork/pypet/pypet/utils/decorators.py", line 163, in new_func
    return func(*args, **kwargs)
  File "/home/hoffmann/dev/pypet-fork/pypet/pypet/utils/decorators.py", line 163, in new_func
    return func(*args, **kwargs)
  File "/home/hoffmann/dev/pypet-fork/pypet/pypet/utils/decorators.py", line 121, in new_func
    return func(*args, **kwargs)
  File "/home/hoffmann/dev/pypet-fork/pypet/pypet/trajectory.py", line 2868, in f_store
    max_depth=max_depth)
  File "/home/hoffmann/dev/pypet-fork/pypet/pypet/utils/mpwrappers.py", line 693, in store
    self._put_on_queue(('STORE', args, kwargs))
  File "/home/hoffmann/dev/pypet-fork/pypet/pypet/utils/decorators.py", line 235, in new_func
    result = func(*args, **kwargs)
  File "/home/hoffmann/dev/pypet-fork/pypet/pypet/utils/mpwrappers.py", line 683, in _put_on_queue
    self.queue.put(to_put, block=True)
  File "<string>", line 2, in put
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 716, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

**Comment by Felix11H** [comment]
This seems to be related to some memory problem as I had an unreasonably large spike count in my simulation that I was trying to save. I'm closing this for now.
