### ISSUE TITLE
pandas error: cannot import name 'Panel4D'

### ISSUE THREAD

**Issue by dilawar** [SmokinCaterpillar/pypet#54]
```
Traceback (most recent call last):
  File "exp_with_pypet.py", line 18, in <module>
    from pypet import Environment, Trajectory
  File "/home1/dilawars/.local/lib/python3.6/site-packages/pypet/__init__.py", line 13, in <module>
    from pypet.environment import Environment, MultiprocContext
  File "/home1/dilawars/.local/lib/python3.6/site-packages/pypet/environment.py", line 69, in <module>
    from pypet.trajectory import Trajectory
  File "/home1/dilawars/.local/lib/python3.6/site-packages/pypet/trajectory.py", line 25, in <module>
    from pypet.parameter import BaseParameter, Parameter, Result
  File "/home1/dilawars/.local/lib/python3.6/site-packages/pypet/parameter.py", line 70, in <module>
    from pandas import DataFrame, Series, Panel, Panel4D
ImportError: cannot import name 'Panel4D'
```
my pandas is version (0.23.1). Do I need to install some other package which is not in dependencies to fix it? Or pandas has deprecated `Panel4D` so I need to go back to old version?

**Comment by dilawar** [comment]
Seems like `Panel4D` has been deprecated https://github.com/pandas-dev/pandas/pull/13776

**Comment by SmokinCaterpillar** [comment]
Yes, seems like it, so as short term solution you could use an older pandas version. The fix in pypet should be easy, I'm going to look into this.

**Comment by dilawar** [comment]
I already have made changes. I'll send a PR.

⁣Sent from Blue ​

**Comment by SmokinCaterpillar** [comment]
Thanks, will be merged into master and uploaded to PyPi within the next few days!

**Comment by SmokinCaterpillar** [comment]
Merged into master, will be deployed to PyPi once CI pipeline passed.
